name: Node Test
on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version'
        required: true
      workingDirectory:
        required: false
        type: string
        default: './'
      workingDirectoryDist:
        required: false
        type: string
        default: './dist'
      publishFromDist:
        required: false
        type: boolean
        default: false
      node_version:
        description: 'Node version to use'
        required: false
        type: string
        default: '24'
      prefix:
        description: 'The prefix to use for the version'
        required: false
        default: ''
        type: string
      artifactPath:
        required: false
        type: string
        default: 'dist'
      environment:
        description: 'The environment to use'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Setup Git
      run: |
        git config --global user.name 'Platform Mesh Technical User'
        git config --global user.email 'platform.mesh.tech@gmail.com'
    - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2
      id: app-token
      with:
        app-id: "1415820"
        private-key: ${{ secrets.PM_PUBLISHER_PRIVATE_KEY }}
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        token: ${{ steps.app-token.outputs.token }}
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: https://registry.npmjs.org
    - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
      with:
        name: target
        path: ${{ inputs.artifactPath }}
      continue-on-error: true
    - name: Clean up prefix from version
      run: |
        CLEANED_VERSION=$(echo ${{ inputs.version }} | cut -c$(wc -c <<<"${{ inputs.prefix }}")-) 
        echo "CLEANED_VERSION=$CLEANED_VERSION" >> $GITHUB_ENV
    - name: Publish from dist folder
      if: ${{ inputs.publishFromDist }}
      run: |
        npm version ${{ env.CLEANED_VERSION }}
        npm publish --provenance --access public
        cd ..
        npm version ${{ env.CLEANED_VERSION }} -m "[no ci] Release ${{ env.CLEANED_VERSION }}"
      working-directory:
        ${{ inputs.workingDirectoryDist }}
    - name: Publish to npmjs
      if: ${{ !inputs.publishFromDist }}
      run: |
        npm version ${{ env.CLEANED_VERSION }} -m "[no ci] Release ${{ env.CLEANED_VERSION }}"
        npm publish --provenance --access public
      working-directory:
        ${{ inputs.workingDirectory }}
    - name: Commit and Tag
      if: inputs.workingDirectory != './'
      run: |
        git add .
        git commit -m "[no ci] Release ${{ env.CLEANED_VERSION }}"
        git fetch
        git rebase
    - name: Push
      run: |
        git push origin
      working-directory: ${{ inputs.workingDirectory }}
