name: OpenSSF Scorecard
on:
  push:
    branches: [main]
  schedule:
    # Weekly on Mondays at 04:30 UTC.
    - cron: '30 4 * * 1'
  workflow_dispatch:

permissions: read-all

jobs:
  scorecard:
    uses: ./.github/workflows/job-ossf-scorecard.yml
    permissions:
      # Needed for Code scanning upload
      security-events: write
      # Needed for GitHub OIDC token if publish_results is true
      id-token: write
